### ISSUE TITLE
history viewer is hardly linked to qwat

### ISSUE THREAD

**Issue by haubourg** [qwat/pg-history-viewer#1]
Looking at how much the plugin is linked to qwat , I see that we do have some hardcoded references to qwat:
- 3 for plugin name (cosmetic issues)
- 2 only in real code:
  - /event_dialog.py (line 279). the query should be easily parameterized on schema name since it is choosen at project configuration stage. 
    
    -line 391:  SELECT qwat_sys.replay_event({}). This is purely specific to QWAT. 
    As @3nids in asking for an upstream PR to 2nd quandrant for the added trigger for views in PR https://github.com/qwat/qwat-data-model/pull/119 , could we port the replay_events there and then have a 100% portable history viewer?.  How much effort would that be? @mhugo ?

```Searching 11 files for "qwat"

/home/regis/APPS/QGIS_PROFILES/qwat/.qgis2/python/plugins/pg-history-viewer/Makefile:
    1  # global
    2  
    3: PLUGINNAME = qwat_history_viewer
    4  
    5  PY_FILES = main.py **init**.py event_dialog.py config_dialog.py

/home/regis/APPS/QGIS_PROFILES/qwat/.qgis2/python/plugins/pg-history-viewer/**init**.py:
    1  def name():
    2:     return u"QWAT history viewer"
    3  def description():
    4:     return u"QWAT history viewer"
    5  def version():
    6      return u"0.1"

/home/regis/APPS/QGIS_PROFILES/qwat/.qgis2/python/plugins/pg-history-viewer/event_dialog.py:
  277          cur = self.conn.cursor()
  278          # base query
  279:         q = "SELECT event_id, action_tstamp_clk, schema_name || '.' || table_name, action, application_name, row_data, changed_fields FROM qwat_sys.logged_actions l"
  280          # where clause
  281          if len(wheres) > 0:
  ...
  389  
  390          cur = self.conn.cursor()
  391:         cur.execute("SELECT qwat_sys.replay_event({})".format(event_id))
  392          self.conn.commit()
  393  

/home/regis/APPS/QGIS_PROFILES/qwat/.qgis2/python/plugins/pg-history-viewer/metadata.txt:
    1  [general]
    2: name=History viewer for the QWAT project
    3  description=This plugin allows to view audit logs and replay some past events
    4  version=0.1

6 matches across 4 files

```
```


<!---
@huboard:{"order":165.04950495016502,"milestone_order":1,"custom_state":""}
-->

**Comment by haubourg** [comment]
One major blocker for a generic plugin is that it requires integer for primary keys. 
problem lies in replay_event(int) function.  

If we can make it totally generic for integer or text like PK, I think we make it. That awesome plugin deserves that, and many projects could benefit from that.

**Comment by mhugo** [comment]
@haubourg thanks for your analysis. I should have made the check myself before :/
* References in names to QWAT are now fixed
* the audit table name now comes from the configuration dialog
* I've added a combo box to select the replay function from the database.

Regarding PR to https://github.com/2ndQuadrant/audit-trigger it seems this repository is nearly dead, there are already pending PR that are unadressed.
I would be in favor of creating a fork that includes our additions as well as fixes and additions from other PR

**Comment by haubourg** [comment]
@hugo, thanks ford doing that so fast. I will test (not as fast).
2nd Quadrant remains very active in postgres field, I would first try the PR to them because fragmentation is really the first killer in FOSS.

**Comment by mhugo** [comment]
@haubourg I agree. I will propose a PR for the replay_function

> One major blocker for a generic plugin is that it requires integer for primary keys.
problem lies in replay_event(int) function. 

Not sure to understand this. Events are stored with a integer primary key (bigint actually). But the replay_function is agnostic of id types of the auditted table ...

**Comment by mhugo** [comment]
Ah ... there is actually a problem. replay_function assumes the primary key of the auditted table is called "id", which is not always the case ...

**Comment by haubourg** [comment]
Sorry, I forgot to join the stack trace: 
id field (by chance good name) value as no quotes in WHERE clause, and it is a text uuid. 

```
Une erreur est survenue lors de l'éxécution du code Python: 

ProgrammingError: syntax error at or near "c81" LINE 1: ...E9DD2341FF2C8842FE2F5A41' WHERE id=fac70d89-c0b8-4c81-81c7-0...                                                             ^ QUERY:  UPDATE ouvrage.troncon SET geometrie='01020000206A080000040000004F8EDB45C8DC23419E7BC73D12305A41927458162FDD234160FEEA7F05305A412FDA3C7E42DD23410CD0CFBE04305A4151BAF656E9DD2341FF2C8842FE2F5A41' WHERE id=fac70d89-c0b8-4c81-81c7-0bb1ad9de6e2 CONTEXT:  PL/pgSQL function api_maj.replay_event(integer) line 23 at EXECUTE 
Traceback (most recent call last):
  File "/home/regis/APPS/QGIS_PROFILES/qwat/.qgis2/python/plugins/pg-history-viewer/event_dialog.py", line 397, in onReplayEvent
    cur.execute("SELECT {}({})".format(self.replay_function, event_id))
ProgrammingError: syntax error at or near "c81"
LINE 1: ...E9DD2341FF2C8842FE2F5A41' WHERE id=fac70d89-c0b8-4c81-81c7-0...
                                                             ^
QUERY:  UPDATE ouvrage.troncon SET geometrie='01020000206A080000040000004F8EDB45C8DC23419E7BC73D12305A41927458162FDD234160FEEA7F05305A412FDA3C7E42DD23410CD0CFBE04305A4151BAF656E9DD2341FF2C8842FE2F5A41' WHERE id=fac70d89-c0b8-4c81-81c7-0bb1ad9de6e2
CONTEXT:  PL/pgSQL function api_maj.replay_event(integer) line 23 at EXECUTE



Version de Python : 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609] 
Version de QGIS : 2.16.3 Nødebo, b7fe4bb2 
```

**Comment by mhugo** [comment]
Ah I see. Thanks. I'll have a look.

**Comment by haubourg** [comment]
@BTW if you're on your way to commit a PR to upstream 2ndQuadrant repo, we need to fetch also the audit_view function added by @sylvainbeo but still pending in  PR #119 .

**Comment by mhugo** [comment]
https://github.com/qwat/qwat-data-model/pull/129

**Comment by 3nids** [comment]
Thanks a lot for the work in the area and sorry for being not more active.

@haubourg regarding fragmentation, qwat uses a slighty modified of the trigger function from 2ndQuadrant since it was not working outside of public schema. I tried once to get this fixed, but seeing the history of upstream repo, it's probaby still no ok. Can you have a look into this?

+1 to bring the whole thing upstream on my side and probably QWAT group.

**Comment by haubourg** [comment]
@3nids Hi Denis, I have used audit trigger outside of public schema before. Probably we have another search_path issue.  
I tried to port it to another application and face one issue:  the hstore fields for old and new data are  empty. I submitted the issue here https://github.com/qwat/qwat-data-model/pull/119 since I couldn't find a solution by myself

**Comment by 3nids** [comment]
I suppose Sylvain tested it before (I didn't). Let's wait on his comment.

**Comment by haubourg** [comment]
For the record, we now have a working code even for views with multiples identifier columns. Code is here 
https://github.com/haubourg/audit-trigger/
it cumulates all 2nd Quandrant pending requests + QWAT work. Some more testing and I'll PR that upstream.

**Comment by haubourg** [comment]
Update , audit.sql has been forked to Oslandia's repo.
