### ISSUE TITLE
[BUG] Activate filter breaks the visualising part

### ISSUE THREAD

**Issue by ponceta** [qwat/pg-history-viewer#19]
On QGIS 2.18.13, win 7 x64.

![history_viewer_filter](https://user-images.githubusercontent.com/8614223/30734715-abd23394-9f7c-11e7-9aec-958801bc190a.gif)

Activating filter breaks the right panel.

**Comment by lbartoletti** [comment]
@ponceta please, can you confirm it with the last version?

**Comment by ponceta** [comment]
This has been fixed, confirmed in 2.2
