### ISSUE TITLE
Once having replayed one event, the dialog becomes unresponsive 

### ISSUE THREAD

**Issue by haubourg** [qwat/pg-history-viewer#3]
After having successfully replayed one event, clicking on the event table will not refresh geometries in the dialog and not either zoom to the right place in the canvas when the option is checked

**Comment by dsavary** [comment]
the same problem, after a search in the left panel (row of event), the "right" dialog (expose the value) become unresponsive

**Comment by haubourg** [comment]
Seems correct, I couldn't reproduce anymore

**Comment by lbartoletti** [comment]
https://github.com/qwat/pg-history-viewer/pull/15
