### ISSUE TITLE
Old / new geometries should have a meaningfull color code + legend

### ISSUE THREAD

**Issue by haubourg** [qwat/pg-history-viewer#4]
It's not easy to guess if red rubberband is the new or old geometry and which one will be actually replayed. 
I would choose blue for new geom and maybe (not sure) orange for old one. 
A text legend could be set in next to the "geometry" frame with something like:

> geometry - orange = old / blue = new geom (will be restored when replaying event)

**Comment by haubourg** [comment]
Ok for me, that a lot more readable, thx Clément!

**Comment by lbartoletti** [comment]
https://github.com/qwat/pg-history-viewer/pull/15
