### ISSUE TITLE
DB connection raises error if user and password not stored

### ISSUE THREAD

**Issue by haubourg** [qwat/pg-history-viewer#7]
For users not storing user and password in connection settings, an error is raised because the prompt is not forwarded to the user. 
This is quite important since most serious install work this way. 
We should also test how it behaves with authentication stored in the security database of qgis.

**Comment by dsavary** [comment]
fix for the futur release ?

**Comment by lbartoletti** [comment]
Fixed in https://github.com/qwat/pg-history-viewer/pull/15
