### ISSUE TITLE
Allow to reuse current connection when transaction groups are activated 

### ISSUE THREAD

**Issue by haubourg** [qwat/pg-history-viewer#8]
Transaction groups allow to execute all transactions in one group for all layers, and thus evaluates trigger results on the fly. Currently, Pg_history will only use existing connections to open a new one (not sure). Being able to replay edits  inside the transaction group would be nice.  (another better option would be to improve transaction groups so that it uses savepoints and allows the UNDO / REDO native actions of edit buffer so that pg_history is not needed here)

**Comment by haubourg** [comment]
Followup, undo redo is being implemented in https://github.com/qgis/QGIS-Enhancement-Proposals/issues/97 funded by QGIS.org grant applications.

**Comment by lbartoletti** [comment]
https://github.com/qwat/pg-history-viewer/pull/15
