### ISSUE TITLE
Replay function

### ISSUE THREAD

**Issue by aileenheal** [qwat/pg-history-viewer#9]
I can't see any documentation as to what the replay function (as specified in the configuration dialog) should be. It is obviously looking for a PostgreSQL function but it unclear what that function would be and where I would find the code to create it.

Some guidance would be gratefully received.

**Comment by dsavary** [comment]
I have the same problem. I don't find the documentation to configure the plugin. 
Can you help me where I can find the "replay function" ?

**Comment by mhugo** [comment]
There is still a pending Pull Request here to introduce this function:
see https://github.com/2ndQuadrant/audit-trigger/pull/26/files#diff-333748ef0aed216a069a4d2788f42a46R289

**Comment by haubourg** [comment]
facing an unresponsive upstream repository, we decided to package the plugin with the sql script to create the audit system functions, including the replay function. 
See 0e8652910a2f8f070915782664add11048cd5edf

**Comment by haubourg** [comment]
Readme improved in 3f7a474ded56bdad58c37e23a6853ee878b5ea94

**Comment by 3nids** [comment]
I would rather be in favor of creating a fork. If their repo is dead, let's make a new one and try to bring the other PR with and tell their authors we have a new repo. What do you think?

**Comment by haubourg** [comment]
@mhugo any thought? 
My main concern is which organisation should host the repo for long term stability? Oslandia, QWAT, Dalibo?

**Comment by mhugo** [comment]
Hi. I would agree with @3nids to make a fork rather than an inclusion in plugin sources, since it could be reused outside this plugin.
I would say Oslandia or QWAT as the hosting organisation, no particular preferences. Moving or forking a repository is an easy task, so it should not be a problem to change in the future.

**Comment by haubourg** [comment]
Finally I forked the audit trigger functions to their new home!
 https://github.com/Oslandia/audit_trigger
